[package]
name = "melee-dat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gc-gcm = "0.10"
insta = "1.14.0"
binrw = "0.8"
